general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
size = 11

[window]
opacity = 0.8
decorations = "None"

[cursor]
style = { shape = "Block", blinking = "Never" }
